--- #YAML:1.0
name:                MooseX-MutatorAttributes
version:             0.12
abstract:            Moose Role to add a quick set method that returns self
license:             ~
author:              
    - ben hengst <notbenh@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp::Assert::More:            0
    Moose:                         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
