--- #YAML:1.0
name:                MooseX-MutatorAttributes
version:             0.02
abstract:            Moose Role to add a quick set method that returns self
license:             ~
author:              
    - ben hengst <notbenh@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Moose:                         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
